#!/usr/bin/ruby

require 'rubygems'
require 'bundler/setup'
require 'ox'
require 'yajl'
$:.unshift File.expand_path "../lib", __FILE__
require 'movie'
require 'parser'

# TODO:
#   save page name (link target) for people and movies
#   parse redirects to do aliases
# FIXME:
#   - John Robinson, James Brown
#     - Two people with the link text "John Robinson" but different page names

Parser.debug = true
parser = Parser.new do |movie|
	puts movie.to_json
end
Ox.sax_parse(parser, ARGF, :skip => :skip_none)
